i2c_master Class Reference
Driver class for an I2C (also known as TWI) bus on an AVR processor.
#include <i2c_master.h>
Public Member Functions
i2c_master (emstream *=NULL)
This constructor creates an I2C driver object.
bool start (void)
Cause a start condition on the I2C bus.
bool restart (void)
Cause a repeated start condition on the I2C bus.
bool stop (void)
Cause a stop condition on the I2C bus.
bool write (uint8_t address, uint8_t reg, uint8_t data)
Write one byte to a slave device on the I2C bus.
bool write (uint8_t address, uint8_t reg, uint8_t *p_buf, uint8_t count)
Write a bunch of bytes to a slave device on the I2C bus.
uint8_t read (uint8_t address, uint8_t reg)
Read one byte from a slave device on the I2C bus.
bool read (uint8_t address, uint8_t reg, uint8_t *p_buffer, uint8_t count)
Read multiple bytes from a slave device on the I2C bus.
bool write_byte (uint8_t byte)
Send a byte to a device on the I2C bus.
uint8_t read_byte (bool ack)
Receive a byte from a device on the I2C bus.
bool check_SDA (void)
Check the status of the SDA line.
bool ping (uint8_t address)
Check if a device is located at the given address.
void scan (emstream *p_ser)
Scan the I2C bus, pinging each address, and print the results.
void take_mutex (void)
Take the mutex associated with this I2C bus.
void give_mutex (void)
Give back the mutex associated with this I2C bus.
Protected Attributes
emstream * p_serial
This is a pointer to a serial port object which is used for debugging the code.
SemaphoreHandle_t mutex
Mutex used to prevent simultaneous uses of the I2C port.
Detailed Description
Driver class for an I2C (also known as TWI) bus on an AVR processor.
It encapsulates basic I2C functionality such as the ability to send and receive bytes through the TWI bus. Currently only operation of the AVR as an I2C bus master is supported; this is what's needed for the AVR to interface with most I2C based sensors.
Definition at line 94 of file i2c_master.h.
Constructor & Destructor Documentation
i2c_master::i2c_master (emstream * p_debug_port = NULL)
This constructor creates an I2C driver object.
Parameters
p_debug_port A serial port, often RS-232, for debugging text (default: NULL)
Definition at line 49 of file i2c_master.cpp.
References I2C_DBG, I2C_TWBR_VALUE, mutex, and p_serial.
Member Function Documentation
bool i2c_master::check_SDA (void)
Check the status of the SDA line.
This method just finds whether the SDA line is currently high or low. This method may be needed when some sensors may need to wait for the SDA line to be directly manipulated by the sensor to indicate that data is available.
Returns
true if the SDA line is high, false if it is low
Definition at line 378 of file i2c_master.cpp.
void i2c_master::give_mutex (void) [inline]
Give back the mutex associated with this I2C bus.
This method gives the mutex which controls access to this I2C bus. It's a complement for the take_mutex() method.
Definition at line 168 of file i2c_master.h.
References mutex.
bool i2c_master::ping (uint8_t address)
Check if a device is located at the given address.
This method causes an I2C start, then sends the given address and checks for an acknowledgement. After that, it just sends a stop condition.
Parameters
address The I2C address for the device. The address should already have been shifted so that it fills the 7 most significant bits of the byte.
Returns
true if a device acknowledged the given address, false if not
Definition at line 400 of file i2c_master.cpp.
References mutex, start(), stop(), and write_byte().
Referenced by scan().
uint8_t i2c_master::read (uint8_t address, uint8_t reg)
Read one byte from a slave device on the I2C bus.
This method reads a single byte from the device on the I2C bus at the given address.
Parameters
address The I2C address for the device. The address must already have been shifted so that it fills the 7 most significant bits of the byte.
reg The register address within the device from which to read
Returns
The byte which was read from the device
Definition at line 223 of file i2c_master.cpp.
References I2C_DBG, mutex, read_byte(), start(), stop(), and write_byte().
Referenced by imu_drv::getEulerAng(), imu_drv::getSysStatus(), and imu_drv::imu_drv().
bool i2c_master::read (uint8_t address, uint8_t reg, uint8_t * p_buffer, uint8_t count)
Read multiple bytes from a slave device on the I2C bus.
This method reads multiple bytes from the device on the I2C bus at the given address.
Parameters
address The I2C address for the device. The address should already have been shifted so that it fills the 7 most significant bits of the byte.
reg The register address within the device from which to read
p_buffer A pointer to a buffer in which the received bytes will be stored
count The number of bytes to read from the device
Returns
true if a problem occurred during reading, false if things went OK
Definition at line 264 of file i2c_master.cpp.
References I2C_DBG, mutex, read_byte(), start(), stop(), and write_byte().
uint8_t i2c_master::read_byte (bool ack)
Receive a byte from a device on the I2C bus.
This method receives a byte from the I2C bus. Other code must have already run the start() command and sent and address byte which got the other device's attention.
Parameters
ack true if we are to end our data request with ACK, telling the slave that we want more data after this; false if we end our data request with NACK, telling the slave that we don't want more data after this
Returns
The byte which was received from the remote device or 0xFF for an error
Definition at line 180 of file i2c_master.cpp.
Referenced by read().
bool i2c_master::restart (void)
Cause a repeated start condition on the I2C bus.
This method causes a repeated start condition on the I2C bus. This is similar to a regular start condition, except that it occurs during an already running conversation, and a different return code is expected if things go as they should.
Returns
true if there was an error, false if the I2C restart was successful
Definition at line 105 of file i2c_master.cpp.
References I2C_DBG.
void i2c_master::scan (emstream * p_ser)
Scan the I2C bus, pinging each address, and print the results.
This handy dandy utility function scans each address on the I2C bus and prints a display showing the addresses at which devices responded to a `ping` with acknowledgement.
Parameters
p_ser A pointer to a serial device on which the scan results are printed
Definition at line 422 of file i2c_master.cpp.
References ping().
bool i2c_master::start (void)
Cause a start condition on the I2C bus.
This method causes a start condition on the I2C bus. In hardware, a start condition means that the SDA line is dropped while the SCL line stays high. This gets the attention of all the other devices on the bus so that they will listen for their addresses.
Returns
true if there was an error, false if the I2C start was successful
Definition at line 73 of file i2c_master.cpp.
Referenced by ping(), read(), and write().
bool i2c_master::stop (void) [inline]
Cause a stop condition on the I2C bus.
This method causes a stop condition on the I2C bus. It's inline because causing a stop condition is a one-liner (in C++ and even in assembly).
Returns
false meaning OK because there's no test to show an error
Definition at line 119 of file i2c_master.h.
Referenced by ping(), read(), and write().
void i2c_master::take_mutex (void) [inline]
Take the mutex associated with this I2C bus.
This method takes the mutex which controls access to this I2C bus. The mutex is automatically taken by the read() and write() commands, but when a device driver needs to use the read_byte() and write_byte() commands directly, that driver needs to handle the mutex with this command and the give_mutex() command.
Definition at line 159 of file i2c_master.h.
References mutex.
bool i2c_master::write (uint8_t address, uint8_t reg, uint8_t data)
Write one byte to a slave device on the I2C bus.
This method writes a single byte to the device on the I2C bus at the given address.
Parameters
address The I2C address for the device. The address should already have been shifted so that it fills the 7 most significant bits of the byte.
reg The register address within the device to which to write
data The byte of data to be written to the device
Returns
true if there were problems or false if everything worked OK
Definition at line 310 of file i2c_master.cpp.
References I2C_DBG, mutex, start(), stop(), and write_byte().
Referenced by imu_drv::setOpMode(), imu_drv::setPwrMode(), and imu_drv::setUnits().
bool i2c_master::write (uint8_t address, uint8_t reg, uint8_t * p_buf, uint8_t count)
Write a bunch of bytes to a slave device on the I2C bus.
This method writes a number of bytes to the device on the I2C bus at the given address.
Parameters
address The I2C address for the device. The address should already have been shifted so that it fills the 7 most significant bits of the byte.
reg The register address within the device to which to write
p_buf Pointer to a memory address at which is found the bytes of data to be written to the device
count The number of bytes to be written from the buffer to the device
Returns
true if there were problems or false if everything worked OK
Definition at line 342 of file i2c_master.cpp.
References I2C_DBG, mutex, start(), stop(), and write_byte().
bool i2c_master::write_byte (uint8_t byte)
Send a byte to a device on the I2C bus.
This method performs an I2C send to transfer a byte to a remote device. The expected response code varies depending on what is being sent at what time; some examples of expected responses are as follows:
0x18 - When one has sent SLA+W, a slave address for a write command, and a good ACK has been received
0x40 - When one has sent SLA+R, a slave address for a read command, and a good ACK has been received
0x28 - When one has transmitted a data byte and received a good ACK
Parameters
byte The byte which is being sent to the remote device
Returns
true if an acknowledge bit was detected, false if none was seen
Definition at line 143 of file i2c_master.cpp.
References I2C_DBG.
Referenced by ping(), read(), and write().
The documentation for this class was generated from the following files:
i2c_master.h
i2c_master.cpp