task_control Class Reference
This define prevents this .H file from being included multiple times in a .CPP file.
#include <task_control.h>
Public Member Functions
task_control (const char *, unsigned portBASE_TYPE, size_t, emstream *)
No private variables or methods for this class.
void run (void)
This method is called by the RTOS once to run the task loop indefinetly.
Detailed Description
This define prevents this .H file from being included multiple times in a .CPP file.
Definition at line 31 of file task_control.h.
Constructor & Destructor Documentation
task_control::task_control (const char * a_name, unsigned portBASE_TYPE a_priority, size_t a_stack_size, emstream * p_ser_dev)
No private variables or methods for this class.
No protected variables or methods for this class This constructor creates a generic control task of which many copies can be made.
This constructor creates a task which controls the output of two pid loops and operates major route features. The main job of this constructor is to call the constructor of parent class (frt_task); the parent's constructor the work.
Parameters
a_name A character string which will be the name of this task
a_priority The priority at which this task will initially run (default: 0)
a_stack_size The size of this task's stack in bytes (default: configMINIMAL_STACK_SIZE)
p_ser_dev Pointer to a serial device (port, radio, SD card, etc.) which can be used by this task to communicate (default: NULL)
Definition at line 25 of file task_control.cpp.
Member Function Documentation
void task_control::run (void)
This method is called by the RTOS once to run the task loop indefinetly.
This method is called once by the RTOS scheduler. Each time around the for (;;) loop, it instantiates the PID objects for the motors and sets the velocities of the motors based on the shared setpoint variable. The circular and linear routing calculations are called and used here to set the proper setpoints for the motor and servo.
Definition at line 38 of file task_control.cpp.
References pid::compute(), pid::PI, routes::servo_power(), pid::set_config(), sh_motor_1_speed, sh_motor_2_speed, and sh_power_set_flag.
The documentation for this class was generated from the following files:
task_control.h
task_control.cpp