task_sensor Class Reference
This define prevents this .H file from being included multiple times in a .CPP file.
#include <task_sensor.h>
Public Member Functions
task_sensor (const char *, unsigned portBASE_TYPE, size_t, emstream *)
No private variables or methods for this class.
void run (void)
This method is called by the RTOS once to run the task loop indefinetly.
Detailed Description
This define prevents this .H file from being included multiple times in a .CPP file.
Definition at line 31 of file task_sensor.h.
Constructor & Destructor Documentation
task_sensor::task_sensor (const char * a_name, unsigned portBASE_TYPE a_priority, size_t a_stack_size, emstream * p_ser_dev)
No private variables or methods for this class.
No protected variables or methods for this class This constructor creates a generic sensor task of which many copies can be made.
This constructor creates a task which creates an IMU sensor and adc objects that give IR sensor readings. The main job of this constructor is to call the constructor of parent class (frt_task); the parent's constructor the work.
Parameters
a_name A character string which will be the name of this task
a_priority The priority at which this task will initially run (default: 0)
a_stack_size The size of this task's stack in bytes (default: configMINIMAL_STACK_SIZE)
p_ser_dev Pointer to a serial device (port, radio, SD card, etc.) which can be used by this task to communicate (default: NULL)
Definition at line 26 of file task_sensor.cpp.
Member Function Documentation
void task_sensor::run (void)
This method is called by the RTOS once to run the task loop indefinetly.
This method is called once by the RTOS scheduler. Each time around the for (;;) loop, it instatiates a new IMU object and two adc objects for IR distance readings. Make a variable which will hold times to use for precise task scheduling
Creates adc objects for IR distance sensors
Creates a new IMU object
Initializes the sensor reading variables
Main task loop
First paraemter is channel of ADC to read from Second parameter is number of samples to take
Calls the system status method in the imu_drv which prints a message regarding the status
Gets the Euler angle variables by calling the getEulerAng method in the imu_drv.
Saves Euler heading reading to a shared variable
Definition at line 37 of file task_sensor.cpp.
References imu_drv::getEulerAng(), imu_drv::getSysStatus(), and adc::read_oversampled().
The documentation for this class was generated from the following files:
task_sensor.h
task_sensor.cpp