imu_drv Class Reference
This class will enable the 9 DOF IMU breakout board with the ME 405 board.
#include <imu_drv.h>
Public Types
enum imu_reg {
*
BNO055_PAGE_ID_ADDR = 0X07,
BNO055_CHIP_ID_ADDR = 0x00,
BNO055_ACCEL_REV_ID_ADDR = 0x01,
BNO055_MAG_REV_ID_ADDR = 0x02,
*
BNO055_GYRO_REV_ID_ADDR = 0x03,
BNO055_SW_REV_ID_LSB_ADDR = 0x04,
BNO055_SW_REV_ID_MSB_ADDR = 0x05,
BNO055_BL_REV_ID_ADDR = 0X06,
*
BNO055_ACCEL_DATA_X_LSB_ADDR = 0X08,
BNO055_ACCEL_DATA_X_MSB_ADDR = 0X09,
BNO055_ACCEL_DATA_Y_LSB_ADDR = 0X0A,
BNO055_ACCEL_DATA_Y_MSB_ADDR = 0X0B,
*
BNO055_ACCEL_DATA_Z_LSB_ADDR = 0X0C,
BNO055_ACCEL_DATA_Z_MSB_ADDR = 0X0D,
BNO055_MAG_DATA_X_LSB_ADDR = 0X0E,
BNO055_MAG_DATA_X_MSB_ADDR = 0X0F,
*
BNO055_MAG_DATA_Y_LSB_ADDR = 0X10,
BNO055_MAG_DATA_Y_MSB_ADDR = 0X11,
BNO055_MAG_DATA_Z_LSB_ADDR = 0X12,
BNO055_MAG_DATA_Z_MSB_ADDR = 0X13,
*
BNO055_GYRO_DATA_X_LSB_ADDR = 0X14,
BNO055_GYRO_DATA_X_MSB_ADDR = 0X15,
BNO055_GYRO_DATA_Y_LSB_ADDR = 0X16,
BNO055_GYRO_DATA_Y_MSB_ADDR = 0X17,
*
BNO055_GYRO_DATA_Z_LSB_ADDR = 0X18,
BNO055_GYRO_DATA_Z_MSB_ADDR = 0X19,
BNO055_EULER_H_LSB_ADDR = 0X1A,
BNO055_EULER_H_MSB_ADDR = 0X1B,
*
BNO055_EULER_R_LSB_ADDR = 0X1C,
BNO055_EULER_R_MSB_ADDR = 0X1D,
BNO055_EULER_P_LSB_ADDR = 0X1E,
BNO055_EULER_P_MSB_ADDR = 0X1F,
*
BNO055_QUATERNION_DATA_W_LSB_ADDR = 0X20,
BNO055_QUATERNION_DATA_W_MSB_ADDR = 0X21,
BNO055_QUATERNION_DATA_X_LSB_ADDR = 0X22,
BNO055_QUATERNION_DATA_X_MSB_ADDR = 0X23,
*
BNO055_QUATERNION_DATA_Y_LSB_ADDR = 0X24,
BNO055_QUATERNION_DATA_Y_MSB_ADDR = 0X25,
BNO055_QUATERNION_DATA_Z_LSB_ADDR = 0X26,
BNO055_QUATERNION_DATA_Z_MSB_ADDR = 0X27,
*
BNO055_LINEAR_ACCEL_DATA_X_LSB_ADDR = 0X28,
BNO055_LINEAR_ACCEL_DATA_X_MSB_ADDR = 0X29,
BNO055_LINEAR_ACCEL_DATA_Y_LSB_ADDR = 0X2A,
BNO055_LINEAR_ACCEL_DATA_Y_MSB_ADDR = 0X2B,
*
BNO055_LINEAR_ACCEL_DATA_Z_LSB_ADDR = 0X2C,
BNO055_LINEAR_ACCEL_DATA_Z_MSB_ADDR = 0X2D,
BNO055_GRAVITY_DATA_X_LSB_ADDR = 0X2E,
BNO055_GRAVITY_DATA_X_MSB_ADDR = 0X2F,
*
BNO055_GRAVITY_DATA_Y_LSB_ADDR = 0X30,
BNO055_GRAVITY_DATA_Y_MSB_ADDR = 0X31,
BNO055_GRAVITY_DATA_Z_LSB_ADDR = 0X32,
BNO055_GRAVITY_DATA_Z_MSB_ADDR = 0X33,
*
BNO055_TEMP_ADDR = 0X34,
BNO055_CALIB_STAT_ADDR = 0X35,
BNO055_SELFTEST_RESULT_ADDR = 0X36,
BNO055_INTR_STAT_ADDR = 0X37,
*
BNO055_SYS_CLK_STAT_ADDR = 0X38,
BNO055_SYS_STAT_ADDR = 0X39,
BNO055_SYS_ERR_ADDR = 0X3A,
BNO055_UNIT_SEL_ADDR = 0X3B,
*
BNO055_DATA_SELECT_ADDR = 0X3C,
BNO055_OPR_MODE_ADDR = 0X3D,
BNO055_PWR_MODE_ADDR = 0X3E,
BNO055_SYS_TRIGGER_ADDR = 0X3F,
*
BNO055_TEMP_SOURCE_ADDR = 0X40,
BNO055_AXIS_MAP_CONFIG_ADDR = 0X41,
BNO055_AXIS_MAP_SIGN_ADDR = 0X42,
BNO055_SIC_MATRIX_0_LSB_ADDR = 0X43,
*
BNO055_SIC_MATRIX_0_MSB_ADDR = 0X44,
BNO055_SIC_MATRIX_1_LSB_ADDR = 0X45,
BNO055_SIC_MATRIX_1_MSB_ADDR = 0X46,
BNO055_SIC_MATRIX_2_LSB_ADDR = 0X47,
*
BNO055_SIC_MATRIX_2_MSB_ADDR = 0X48,
BNO055_SIC_MATRIX_3_LSB_ADDR = 0X49,
BNO055_SIC_MATRIX_3_MSB_ADDR = 0X4A,
BNO055_SIC_MATRIX_4_LSB_ADDR = 0X4B,
*
BNO055_SIC_MATRIX_4_MSB_ADDR = 0X4C,
BNO055_SIC_MATRIX_5_LSB_ADDR = 0X4D,
BNO055_SIC_MATRIX_5_MSB_ADDR = 0X4E,
BNO055_SIC_MATRIX_6_LSB_ADDR = 0X4F,
*
BNO055_SIC_MATRIX_6_MSB_ADDR = 0X50,
BNO055_SIC_MATRIX_7_LSB_ADDR = 0X51,
BNO055_SIC_MATRIX_7_MSB_ADDR = 0X52,
BNO055_SIC_MATRIX_8_LSB_ADDR = 0X53,
*
BNO055_SIC_MATRIX_8_MSB_ADDR = 0X54,
ACCEL_OFFSET_X_LSB_ADDR = 0X55,
ACCEL_OFFSET_X_MSB_ADDR = 0X56,
ACCEL_OFFSET_Y_LSB_ADDR = 0X57,
*
ACCEL_OFFSET_Y_MSB_ADDR = 0X58,
ACCEL_OFFSET_Z_LSB_ADDR = 0X59,
ACCEL_OFFSET_Z_MSB_ADDR = 0X5A,
MAG_OFFSET_X_LSB_ADDR = 0X5B,
*
MAG_OFFSET_X_MSB_ADDR = 0X5C,
MAG_OFFSET_Y_LSB_ADDR = 0X5D,
MAG_OFFSET_Y_MSB_ADDR = 0X5E,
MAG_OFFSET_Z_LSB_ADDR = 0X5F,
*
MAG_OFFSET_Z_MSB_ADDR = 0X60,
GYRO_OFFSET_X_LSB_ADDR = 0X61,
GYRO_OFFSET_X_MSB_ADDR = 0X62,
GYRO_OFFSET_Y_LSB_ADDR = 0X63,
*
GYRO_OFFSET_Y_MSB_ADDR = 0X64,
GYRO_OFFSET_Z_LSB_ADDR = 0X65,
GYRO_OFFSET_Z_MSB_ADDR = 0X66,
ACCEL_RADIUS_LSB_ADDR = 0X67,
*
ACCEL_RADIUS_MSB_ADDR = 0X68,
MAG_RADIUS_LSB_ADDR = 0X69,
MAG_RADIUS_MSB_ADDR = 0X6A
 }
enum imu_powermode_t { POWER_MODE_NORMAL = 0X00,
POWER_MODE_LOWPOWER = 0X01,
POWER_MODE_SUSPEND = 0X02
 }
enum imu_opmode_t {
*
OPERATION_MODE_CONFIG = 0X00,
OPERATION_MODE_ACCONLY = 0X01,
OPERATION_MODE_MAGONLY = 0X02,
OPERATION_MODE_GYRONLY = 0X03,
*
OPERATION_MODE_ACCMAG = 0X04,
OPERATION_MODE_ACCGYRO = 0X05,
OPERATION_MODE_MAGGYRO = 0X06,
OPERATION_MODE_AMG = 0X07,
*
OPERATION_MODE_IMUPLUS = 0X08,
OPERATION_MODE_COMPASS = 0X09,
OPERATION_MODE_M4G = 0X0A,
OPERATION_MODE_NDOF_FMC_OFF = 0X0B,
*
OPERATION_MODE_NDOF = 0X0C
 }
enum imu_axis_remap_config {
*
REMAP_CONFIG_P0 = 0x21,
REMAP_CONFIG_P1 = 0x24,
REMAP_CONFIG_P2 = 0x24,
REMAP_CONFIG_P3 = 0x21,
*
REMAP_CONFIG_P4 = 0x24,
REMAP_CONFIG_P5 = 0x21,
REMAP_CONFIG_P6 = 0x21,
REMAP_CONFIG_P7 = 0x24
 }
enum imu_axis_remap_sign {
*
REMAP_SIGN_P0 = 0x04,
REMAP_SIGN_P1 = 0x00,
REMAP_SIGN_P2 = 0x06,
REMAP_SIGN_P3 = 0x02,
*
REMAP_SIGN_P4 = 0x03,
REMAP_SIGN_P5 = 0x01,
REMAP_SIGN_P6 = 0x07,
REMAP_SIGN_P7 = 0x05
 }
typedef enum imu_drv::imu_reg imu_reg_t
typedef enum
*
imu_drv::imu_axis_remap_config imu_axis_remap_config_t
typedef enum
*
imu_drv::imu_axis_remap_sign imu_axis_remap_sign_t
Public Member Functions
imu_drv (emstream *=NULL)
This constructor sets up the 9 DOF IMU object.
void setOpMode (imu_opmode_t mode)
Setter Methods.
void setPwrMode (imu_powermode_t mode)
Sets power mode of IMU.
void setUnits ()
Sets units selection mode of IMU.
void getSysStatus ()
Getter methods.
int16_t getEulerAng (uint8_t data_sel)
Reads Euler angle registers and returns selected value.
Protected Attributes
emstream * p_serial
i2c_master * i2c_comm
Detailed Description
This class will enable the 9 DOF IMU breakout board with the ME 405 board.
This header file defines many of the useful register addresses and some settings assosciated with those registers.
Definition at line 33 of file imu_drv.h.
Member Typedef Documentation
typedef enum imu_drv::imu_reg imu_drv::imu_reg_t
The constructor sets up the IMU driver for use. The `= NULL` part is a default parameter, meaning that if that parameter isn't given on the line where this constructor is called, the compiler will just fill in `NULL`. In this case that has the effect of turning off diagnostic printouts.
Member Enumeration Documentation
enum imu_drv::imu_reg
The constructor sets up the IMU driver for use. The `= NULL` part is a default parameter, meaning that if that parameter isn't given on the line where this constructor is called, the compiler will just fill in `NULL`. In this case that has the effect of turning off diagnostic printouts.
Definition at line 46 of file imu_drv.h.
Constructor & Destructor Documentation
imu_drv::imu_drv (emstream * p_serial_port = NULL)
This constructor sets up the 9 DOF IMU object.
The constructor creates a p_serial object for printing to the serial port and creates a i2c_comm object which allows for communication between the sensor and ME 405 board. The constructor also checks that the i2c_comm object can communicate with the IMU and verifies the address of the IMU. Lastly the constructor sets the default settings of the imu which are nDOF mode, metric units, and normal power mode.
Parameters
p_serial_port A pointer to the serial port which writes debugging info.
Definition at line 29 of file imu_drv.cpp.
References IMU_ADDRESS, p_serial, i2c_master::read(), setOpMode(), setPwrMode(), and setUnits().
Member Function Documentation
int16_t imu_drv::getEulerAng (uint8_t data_sel)
Reads Euler angle registers and returns selected value.
This method returns the Euler angle value desired based on the data select input. An input of 1 returns the heading value, an input of 2 returns the roll value, and an input of 3 returns the pitch value. The values read are 16x the value in degrees so the returned values are divided by 16.
Parameters
data_sel Variable used to pick which Euler angle value (heading, roll, or pitch) is desired.
Definition at line 159 of file imu_drv.cpp.
References IMU_ADDRESS, p_serial, and i2c_master::read().
Referenced by task_imu::run().
void imu_drv::getSysStatus ()
Getter methods.
Reads system status register of the IMU
Prints out the system status of the IMU (numbers correspond to values listed in comments). If an error status is determined then the error message is also printed (numbers correspond to values listed in commments).
Parameters
none
Definition at line 109 of file imu_drv.cpp.
References IMU_ADDRESS, p_serial, and i2c_master::read().
Referenced by task_imu::run().
void imu_drv::setOpMode (imu_opmode_t mode)
Setter Methods.
Sets operation mode of IMU
Changes the operation mode to one of the operation mode values defineed in the header file and prints a confirmation message.
Parameters
mode Variable of imu_opmode type as defined in the header file.
Definition at line 64 of file imu_drv.cpp.
References IMU_ADDRESS, p_serial, and i2c_master::write().
Referenced by imu_drv().
void imu_drv::setPwrMode (imu_powermode_t mode)
Sets power mode of IMU.
Changes the power mode to one of the operation mode values defineed in the header file and prints a confirmation message.
Parameters
mode Variable of imu_powermode type as defined in the header file.
Definition at line 76 of file imu_drv.cpp.
References IMU_ADDRESS, p_serial, and i2c_master::write().
Referenced by imu_drv().
void imu_drv::setUnits ()
Sets units selection mode of IMU.
Sets the units for the acceleration, linear acceleration, and gravity vector to m/s^2. Sets the units for the angular rate to deg/sec. Sets the units for the Euler Angles to degrees and the units for the temperature to degC.
Parameters
none
Definition at line 89 of file imu_drv.cpp.
References IMU_ADDRESS, p_serial, and i2c_master::write().
Referenced by imu_drv().
Member Data Documentation
emstream* imu_drv::p_serial [protected]
The imu class uses this pointer to print debug messages via the serial port and I2C communcations with the sensor.
Definition at line 38 of file imu_drv.h.
Referenced by getEulerAng(), getSysStatus(), imu_drv(), setOpMode(), setPwrMode(), and setUnits().
The documentation for this class was generated from the following files:
imu_drv.h
imu_drv.cpp