pid Class Reference
This class runs a 16-bit fixed point PID.
#include <pid.h>
Classes
struct config
This struct defines a pid configuration.
Public Types
enum mode {
*
OFF = (0x00<<0),
P = (0x01<<0),
PI = (0x02<<0),
PD = (0x03<<0),
*
PID = (0x04<<0),
MANUAL = (0x05<<0)
 }
This enumeration defines possible modes of operation.
typedef enum pid::mode mode_t
This enumeration defines possible modes of operation.
typedef struct pid::config config_t
This struct defines a pid configuration.
Public Member Functions
pid (emstream *)
This constructor sets up a 16-bit PID controller.
void set_mode (mode_t mode)
This method sets the PID mode.
void set_input (int16_t input)
Updates the input to the PID, the value we are trying to control.
void set_output (int16_t output)
Manually updates the control output value.
void set_setpoint (int16_t setpoint)
Updates the set-point for the PID.
void set_config (config_t config)
Updates the PID configuration and clears esum, resetting the PID controller.
void set_Kp (int16_t Kp)
Updates the proportional gain.
void set_Ki (int16_t Ki)
Updates the integral gain.
void set_Kd (int16_t Kd)
Updates the derivative gain.
void set_Kw (int16_t Kw)
Updates the anti-windup gain.
void set_saturator (int16_t min, int16_t max)
Updates the upper and lower saturator values.
mode_t get_mode ()
Gets the current mode of the PID.
int16_t get_input ()
Gets the current value of the parameter being controlled by the PID.
int16_t get_output ()
Gets the controller output value.
int16_t get_setpoint ()
Gets the current PID setpoint value.
config_t get_config ()
Gets the controller configuration.
int16_t get_Kp ()
Gets the proportional gain.
int16_t get_Ki ()
Gets the integral gain.
int16_t get_Kd ()
Gets the derivative gain.
int16_t get_Kw ()
Gets the anti-windup gain.
int16_t get_saturator_min ()
Gets the saturator minimum.
int16_t get_saturator_max ()
Gets the saturator maximum.
int16_t compute ()
Computes the new PID output value.
int16_t compute (int16_t new_input, int16_t new_setpoint)
Computes the new PID output value.
Protected Attributes
emstream * p_serial
Serial port pointer, used to say hello.
config_t config
config_t containing PID parameters
int16_t input
The value being controlled.
int16_t output
The controller output.
int16_t setpoint
Desired reference value for input.
int16_t error
Error.
int16_t linput
Last input to use for derivative computation.
int16_t dinput
Difference in input value for derivative gain.
int16_t esum
Error Sum.
int16_t saturation
Saturator value.
Detailed Description
This class runs a 16-bit fixed point PID.
The PID controller can run in P, PI, PD, PID, and manual modes. When the integral action is used, a fourth gain, Kw can be used to help eliminate windup problems. To help with reset spikes, the difference computed for the derivative action is on the input value, not the error. The block diagram below shows the entirety of the controller and it's context with respect to the plant. The input and output attributes are from the controller's perspective, not the plant. That is, input is the output of the plant into the controller and output is the input to the plant from the controller.
                               PID CONTROLLER w/ ANTI-WINDUP 
            ##################################################################
            #                          +------+                              #
            #                          |      |                              #
            #                    +-----+  Kw  <--------------------+         #
            #                    |     |      |                 +--+--+      #
            #                 (-)|     +------+              (+)|     |(-)   #
            #                 +--v--+  +------+             +--->  Σ  <---+  #
            #              (+)|     |  |      |             |   |     |   |  #
            #              +-->  Σ  +--> Ki/s +-------+     |   +-----+   |  #
            #              |  |     |  |      |       |     |             |  #
            #              |  +-----+  +------+       |(+)  |        MAX  |  #
            #     +-----+  |           +------+    +--v--+  |  +-------+  |  #        +------ +
  SETPOINT  #  (+)|     |  |           |      | (+)|     |  |  |    -- |  |  # OUTPUT |       |
  ---------->----->  Σ  +--+----------->  Kp  +---->  Σ  +--+-->   /   +--+--+--------> PLANT +----+------>
            #     |     |              |      |    |     |     | --    |     #        |       |    |
            #     +--^--+              +------+    +--^--+     +-------+     #        +------ +    |
            #     (-)|                 +------+    (+)|        MIN           #                     |
  INPUT     #        |                 |      |       |                      #                     |
  +--------->------- +-----------------> Kd*s +-------+                      #                     |
  |         #                          |      |                              #                     |
  |         #                          +------+                              #                     |
  |         ##################################################################                     |
  +------------------------------------------------------------------------------------------------+
 To use the pid controller you must first call the constructor with a pointer to a serial object.
 pid* motor_pid = new pid(p_serial);
 The system parameters must then be set. This can be done using the individual set function for each parameter, or all at once using a configuration struct. For example, we can set the controller to PI mode with gains Ki=5, Kp=2, and Kw=1. Remember that the gains are entered as 1024 times the desired gain to increase resolution. Additionally, we will set the output saturator values to +/- 1600.
 motor_pid->set_config(pid::config_t{PI,5120,2048,0,1024,-1600,1600});
 Now, to run the PID, we must call compute() inside a loop (probably a task) running at a fixed interval. Changing the delay of the task will change the effect of the Ki and Kd gains. Suppose we have three int16_t shares motor_speed, motor_setpoint, and motor_power. We can easily run the PID in one line.
 motor_power->put(motor_pid->compute(motor_speed->get(),motor_setpoint->get()));
Definition at line 81 of file pid.h.
Member Enumeration Documentation
enum pid::mode
This enumeration defines possible modes of operation.
Enumerator
OFF
 Output is zero
P
 Proportional action only
PI
 Proportional and integral action
PD
 Proportional and derivative action
PID
 Full PID action
MANUAL
 Output can be updated manually using set_output()
Definition at line 89 of file pid.h.
Constructor & Destructor Documentation
pid::pid (emstream * p_serial_port)
This constructor sets up a 16-bit PID controller.
The pid is initialized off with all gains set to 0
Parameters
p_serial_port A pointer to the serial port which writes debugging info.
Definition at line 31 of file pid.cpp.
References OFF.
Member Function Documentation
int16_t pid::compute ()
Computes the new PID output value.
This method forces the controller to recompute without updating the input or setpoint
Definition at line 269 of file pid.cpp.
References dinput, error, esum, input, pid::config::Kd, pid::config::Ki, pid::config::Kp, pid::config::Kw, MANUAL, pid::config::max, pid::config::min, pid::config::mode, OFF, output, P, PD, PI, PID, saturation, setpoint, ssadd, ssdiv, ssmul, and sssub.
Referenced by compute().
int16_t pid::compute (int16_t new_input, int16_t new_setpoint)
Computes the new PID output value.
This method uses new actual and reference values to compute the controller output value. The mode and gain settings are considered during the calculation.
Parameters
new_input The new input for the controller. This is the value being controlled
new_setpoint The new setpoint for the controlller. This is the desired value for the input.
Returns
The new output of the PID
Definition at line 258 of file pid.cpp.
References compute(), set_input(), and set_setpoint().
pid::config_t pid::get_config ()
Gets the controller configuration.
Returns
Current controller configuration
Definition at line 191 of file pid.cpp.
References config.
int16_t pid::get_input ()
Gets the current value of the parameter being controlled by the PID.
Returns
Input (value being controlled)
Definition at line 164 of file pid.cpp.
References input.
int16_t pid::get_Kd ()
Gets the derivative gain.
Returns
derivative gain
Definition at line 218 of file pid.cpp.
References pid::config::Kd.
Referenced by operator<<().
int16_t pid::get_Ki ()
Gets the integral gain.
Returns
Integral gain
Definition at line 200 of file pid.cpp.
References pid::config::Ki.
Referenced by operator<<().
int16_t pid::get_Kp ()
Gets the proportional gain.
Returns
Propotional gain
Definition at line 209 of file pid.cpp.
References pid::config::Kp.
Referenced by operator<<().
int16_t pid::get_Kw ()
Gets the anti-windup gain.
Returns
Anti-windup gain
Definition at line 227 of file pid.cpp.
References pid::config::Kw.
Referenced by operator<<().
pid::mode_t pid::get_mode ()
Gets the current mode of the PID.
Returns
The current PID mode
Definition at line 155 of file pid.cpp.
References pid::config::mode.
Referenced by operator<<().
int16_t pid::get_output ()
Gets the controller output value.
Returns
Current controller output
Definition at line 173 of file pid.cpp.
References output.
int16_t pid::get_saturator_max ()
Gets the saturator maximum.
Returns
Maximal controller output value
Definition at line 245 of file pid.cpp.
References pid::config::max.
Referenced by operator<<().
int16_t pid::get_saturator_min ()
Gets the saturator minimum.
Returns
Minimal controller output value
Definition at line 236 of file pid.cpp.
References pid::config::min.
Referenced by operator<<().
int16_t pid::get_setpoint ()
Gets the current PID setpoint value.
Returns
The current PID setpoint value
Definition at line 182 of file pid.cpp.
References setpoint.
void pid::set_config (config_t my_config)
Updates the PID configuration and clears esum, resetting the PID controller.
Parameters
my_config New controller configuration
Definition at line 92 of file pid.cpp.
References esum.
void pid::set_input (int16_t my_input)
Updates the input to the PID, the value we are trying to control.
In addition to updating the input value, it also computes the deriviative
Parameters
my_input New input value
Definition at line 60 of file pid.cpp.
References dinput, input, linput, and sssub.
Referenced by compute().
void pid::set_Kd (int16_t Kd)
Updates the derivative gain.
Parameters
Kd New derivivative gain (1024x the value should be entered to allow fractional gain values.)
Definition at line 123 of file pid.cpp.
References pid::config::Kd.
void pid::set_Ki (int16_t Ki)
Updates the integral gain.
Parameters
Ki New integral gain (1024x the value should be entered to allow fractional gain values.)
Definition at line 113 of file pid.cpp.
References pid::config::Ki.
void pid::set_Kp (int16_t Kp)
Updates the proportional gain.
Parameters
Kp New proportional gain (1024x the value should be entered to allow fractional gain values.)
Definition at line 103 of file pid.cpp.
References pid::config::Kp.
void pid::set_Kw (int16_t Kw)
Updates the anti-windup gain.
Parameters
Kw New anti-windup gain (1024x the value should be entered to allow fractional gain values.)
Definition at line 133 of file pid.cpp.
References pid::config::Kw.
void pid::set_mode (mode_t my_mode)
This method sets the PID mode.
The method sets the PID mode and also clears esum, effectively resetting the PID if the same mode is set again
Parameters
my_mode An enumerated type pid_mode_t describing the new mode for the PID
Definition at line 49 of file pid.cpp.
References esum, and pid::config::mode.
void pid::set_output (int16_t my_output)
Manually updates the control output value.
This method is for updating the PID controller value while it is in manual mode
Parameters
my_output New controller output value
Definition at line 74 of file pid.cpp.
References output.
void pid::set_saturator (int16_t min, int16_t max)
Updates the upper and lower saturator values.
Updates the minimal and maximal values allowed as output from the PID controller.
Parameters
min New minimum value
max New maximum value
Definition at line 145 of file pid.cpp.
References pid::config::max, and pid::config::min.
void pid::set_setpoint (int16_t my_setpoint)
Updates the set-point for the PID.
Parameters
my_setpoint New set-point
Definition at line 83 of file pid.cpp.
References setpoint.
Referenced by compute().
The documentation for this class was generated from the following files:
pid.h
pid.cpp